### ISSUE TITLE
panic when MQTT broker is not running

### ISSUE THREAD

**Issue by anonymouse64** [edgexfoundry/device-mqtt-go#93]
When running device-mqtt without a MQTT broker, a friendly message is printed, but there is still a panic somewhere in the code: 

```
Aug 22 14:14:56 systemd[1]: Started Service for snap application edgex-device-mqtt.device-mqtt.
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: Init: useRegistry: consul://localhost:8500 profile: res confDir: /var/snap/edgex-device-mqtt/x1/config/device-mqtt
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: Check registry is up... http://localhost:8500
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: Register in registry...
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: Calling service.Start.
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: EnableRemote is false, using local log file
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.639659055Z app=edgex-device-mqtt source=init.go:137 msg="Check Metadata service's status ..."
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.639701876Z app=edgex-device-mqtt source=init.go:137 msg="Check Data service's status ..."
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.646675345Z app=edgex-device-mqtt source=init.go:47 msg="Service clients initialize successful."
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.649698772Z app=edgex-device-mqtt source=service.go:135 msg="Trying to find Device Service: edgex-device-mqtt"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.649751462Z app=edgex-device-mqtt source=loader.go:250 msg="listen for config changes from Registry"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.654158009Z app=edgex-device-mqtt source=service.go:149 msg="Device Service edgex-device-mqtt exists"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.656532727Z app=edgex-device-mqtt source=loader.go:274 msg="Writeable configuration has been updated. Setting log level to DEBUG"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.658627786Z app=edgex-device-mqtt source=service.go:152 msg="Device Service in Core MetaData: edgex-device-mqtt"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.666558198Z app=edgex-device-mqtt source=profiles.go:39 msg="created absolute path for loading pre-defined Device Profiles: /var/snap/edgex-device-mqtt/current/config/device-mqtt/res"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.672861268Z app=edgex-device-mqtt source=devices.go:22 msg="Loading pre-define Devices from configuration"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.675785868Z app=edgex-device-mqtt source=restrouter.go:21 msg="init status rest controller"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.675820243Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@0.0.0.0:1883 clientID=CommandResponseSubscriber "
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=INFO ts=2019-08-22T19:14:56.675843807Z app=edgex-device-mqtt source=driver.go:279 msg="Create MQTT client and connection: uri=tcp://admin:public@0.0.0.0:1883 clientID=IncomingDataSubscriber "
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.678805457Z app=edgex-device-mqtt source=restrouter.go:24 msg="init command rest controller"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: level=DEBUG ts=2019-08-22T19:14:56.681865584Z app=edgex-device-mqtt source=restrouter.go:30 msg="init callback rest controller"
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: panic: start command response Listener failed, please check MQTT broker settings are correct, Network Error : dial tcp 0.0.0.0:1883: connect: connection refused
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: goroutine 75 [running]:
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).Initialize.func1()
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]:         /root/parts/device-mqtt/src/internal/driver/driver.go:73 +0xac
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]: created by github.com/edgexfoundry/device-mqtt-go/internal/driver.(*Driver).Initialize
Aug 22 14:14:56 edgex-device-mqtt.device-mqtt[40511]:         /root/parts/device-mqtt/src/internal/driver/driver.go:70 +0xa2
Aug 22 14:14:56 systemd[1]: snap.edgex-device-mqtt.device-mqtt.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

It would be nice if:
- an ERROR level message was logged when this happens
- we didn't panic and instead output a message and exit with `os.Exit(1)`

**Comment by cloudxxx8** [comment]
that's the issue we have to improve.
@weichou1229 please fix this when you have time

**Comment by cloudxxx8** [comment]
@weichou1229 please fix this issue next week
